pipeline {
    agent any

    tools {
        maven 'Maven 3.9'
        jdk   'JDK 21'
    }

    environment {
        APP_NAME = 'pacemate'
        WAR_FILE = "pacemate-javaee/target/${APP_NAME}.war"
    }

    options {
        timestamps()
        timeout(time: 20, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {

        // ── 1. Checkout ──────────────────────────────────────────────
        stage('Checkout') {
            steps {
                checkout scm
                echo "Build #${env.BUILD_NUMBER}"
            }
        }

        // ── 2. Build & Tests ─────────────────────────────────────────
        stage('Build & Test') {
            steps {
                dir('pacemate-javaee') {
                    bat 'mvn clean verify -B -Dpacemate.pu=pacemate-test-pu'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'pacemate-javaee/target/surefire-reports/*.xml'
                }
            }
        }

        // ── 3. Archive du WAR ────────────────────────────────────────
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: "${WAR_FILE}", fingerprint: true
            }
        }
    }

    post {
        success {
            echo "Pipeline réussi — Build #${env.BUILD_NUMBER}"
        }
        failure {
            echo "Pipeline echoue — Build #${env.BUILD_NUMBER}"
        }
        always {
            node('built-in') {
                cleanWs()
            }
        }
    }
}
